### ISSUE TITLE
Failing to build or install by pypi on linux - interp.c ?

### ISSUE THREAD

**Issue by DomagojHack** [bmcfee/resampy#25]
I can see the similar issues being opened for OSX and Windows yet there is still an issue with interp.c.

Here is my output of `sudo pip install resampy`:

```
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.10 in /usr/lib/python2.7/dist-packages (from resampy)
Requirement already satisfied (use --upgrade to upgrade): scipy>=0.13 in /usr/local/lib/python2.7/dist-packages (from resampy)
Requirement already satisfied (use --upgrade to upgrade): six>=1.3 in /usr/lib/python2.7/dist-packages (from resampy)
Requirement already satisfied (use --upgrade to upgrade): Cython>=0.23 in /usr/local/lib/python2.7/dist-packages (from resampy)
Installing collected packages: resampy
  Running setup.py install for resampy ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-4m1Ait/resampy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-m9MyHv-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/resampy
    copying resampy/version.py -> build/lib.linux-x86_64-2.7/resampy
    copying resampy/core.py -> build/lib.linux-x86_64-2.7/resampy
    copying resampy/filters.py -> build/lib.linux-x86_64-2.7/resampy
    copying resampy/__init__.py -> build/lib.linux-x86_64-2.7/resampy
    creating build/lib.linux-x86_64-2.7/resampy/data
    copying resampy/data/kaiser_fast.npz -> build/lib.linux-x86_64-2.7/resampy/data
    copying resampy/data/kaiser_best.npz -> build/lib.linux-x86_64-2.7/resampy/data
    running build_ext
    skipping 'resampy/interp.c' Cython extension (up-to-date)
    building 'resampy.interp' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/resampy
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c resampy/interp.c -o build/temp.linux-x86_64-2.7/resampy/interp.o
    resampy/interp.c:4:20: fatal error: Python.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-4m1Ait/resampy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-m9MyHv-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-4m1Ait/resampy/
```

I've tried to clone the repository run `sudo python install.py build`
Here is this output too:
```
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/resampy
copying resampy/version.py -> build/lib.linux-x86_64-2.7/resampy
copying resampy/core.py -> build/lib.linux-x86_64-2.7/resampy
copying resampy/filters.py -> build/lib.linux-x86_64-2.7/resampy
copying resampy/__init__.py -> build/lib.linux-x86_64-2.7/resampy
creating build/lib.linux-x86_64-2.7/resampy/data
copying resampy/data/kaiser_fast.npz -> build/lib.linux-x86_64-2.7/resampy/data
copying resampy/data/kaiser_best.npz -> build/lib.linux-x86_64-2.7/resampy/data
running build_ext
cythoning resampy/interp.pyx to resampy/interp.c
building 'resampy.interp' extension
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/resampy
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c resampy/interp.c -o build/temp.linux-x86_64-2.7/resampy/interp.o
resampy/interp.c:4:20: fatal error: Python.h: No such file or directory
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

Cython is installed with the latest version available on pypi.

**Comment by DomagojHack** [comment]
Cloning resampy and running `sudo pip install -e resampy` worked for some reason.

**Comment by bmcfee** [comment]
That's really strange.  Can you provide the details of your system (python environment, package versions, compiler, etc)?

**Comment by DomagojHack** [comment]
Well I have fresh install of Ubuntu with default python 2.7, packages were all installed with pip today so they should be up-to-date. I doubt it is environmental problem as installation via pip and git cloning ended successful. There must be an issue with version of Resampy on PyPI or something else.

I propose that README.md should contain different installation instructions, like README.md of librosa package does.

Cheers

**Comment by DomagojHack** [comment]
I will close this as installatio with commands ended successful for me.
 ```
git clone https://github.com/bmcfee/resampy.git
sudo pip install -e resampy
```

**Comment by bmcfee** [comment]
I'm keeping this open, as the pip install ought to work out of the box for this.

**Comment by bmcfee** [comment]
Incidentally, [this thread](http://stackoverflow.com/questions/21530577/fatal-error-python-h-no-such-file-or-directory) seems relevant to your configuration.

Can you please revert and try installing via pip after installing python-dev?  If that turns out to be the problem, then it's not something we can resolve from within a `pip` package and I can close this out.

**Comment by DomagojHack** [comment]
Python-dev was installed before I've tried pip installation.

**Comment by bmcfee** [comment]
Does it only work with `-e`, or does `pip install .` work as well?

**Comment by DomagojHack** [comment]
Didn't try that. But I tested it now and it also worked.

**Comment by bmcfee** [comment]
Interesting.

The build line from your initial report:
```
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv \
    -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time \
    -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat \
    -Werror=format-security -fPIC \
    -I/usr/lib/python2.7/dist-packages/numpy/core/include \
    -I/usr/include/python2.7 \
    -c resampy/interp.c -o build/temp.linux-x86_64-2.7/resampy/interp.o
```

adds two include paths: `/usr/include/python2.7` and `/usr/lib/python2.7/dist-pacakges/numpy/core/include`.  Can you verify that `Python.h` exists in either of those directories on the system where `pip install resampy` fails?

**Comment by DomagojHack** [comment]
My content of ```/usr/include/python2.7``` has Python.h but in other hand, folder ```/usr/lib/python2.7/dist-pacakges/numpy/core/include``` does not exist.

**Comment by bmcfee** [comment]
That's really strange; I can't see why it would fail to find `Python.h` when it's explicitly forcing that directory into the include path.  (The fact that the second folder doesn't exist shouldn't matter for the purposes of the error that you're getting.)

Sorry to keep asking for more output, but can you paste the full log of (failing) `pip install resampy` as well as the install from the local clone of the repo?

**Comment by DomagojHack** [comment]
Failing example runned with

`sudo pip install resampy --verbose`

```Collecting resampy
  1 location(s) to search for versions of resampy:
  * https://pypi.python.org/simple/resampy/
  Getting page https://pypi.python.org/simple/resampy/
  Looking up "https://pypi.python.org/simple/resampy/" in the cache
  No cache entry available
  Starting new HTTPS connection (1): pypi.python.org
  "GET /simple/resampy/ HTTP/1.1" 200 598
  Updating cache with response from "https://pypi.python.org/simple/resampy/"
  Caching b/c date exists and max-age > 0
  Analyzing links from page https://pypi.python.org/simple/resampy/
    Found link https://pypi.python.org/packages/06/70/1afa9af4c9f90f2e36174f227b68b4b5655d830bdd358ac809164e0b3851/resampy-0.1.0rc0.tar.gz#md5=361d0912d11be5eb26289a14dbf61fe1 (from https://pypi.python.org/simple/resampy/), version: 0.1.0rc0
    Found link https://pypi.python.org/packages/2b/5e/3a85b22a52f44709d228aabe0985d674124c23ce9589bd8c27a609c8ad1b/resampy-0.1.3.tar.gz#md5=cafebf87cd908d2a35f2f4ac1e95ddb6 (from https://pypi.python.org/simple/resampy/), version: 0.1.3
    Found link https://pypi.python.org/packages/4b/d1/4f1c74c1e6b41d1eda6c8c1b7d0227409fb808c7d39f5447d06c679076b3/resampy-0.1.2.tar.gz#md5=930c1ddc0d240b37044e498eabdca78c (from https://pypi.python.org/simple/resampy/), version: 0.1.2
    Found link https://pypi.python.org/packages/7f/05/af22d8e404f675980f6413ebbc570e1bacc8034e918c5e3038e99bec3ed7/resampy-0.1.1-final.tar.gz#md5=ffb51b523a4a0eabd08c12e921997571 (from https://pypi.python.org/simple/resampy/), version: 0.1.1-final
    Found link https://pypi.python.org/packages/e1/8d/9fbc8e1dba8a83e4be47cc4a906dcb3ca5959bc7e4da1d388e64c2d20a5e/resampy-0.1.0.tar.gz#md5=3fec740b9dcc40397efd4d1b4e4ad532 (from https://pypi.python.org/simple/resampy/), version: 0.1.0
    Found link https://pypi.python.org/packages/ee/02/d6b9d504dda712cd79f69351a1f657056377b372c5aa3213ae2e97e7f45d/resampy-0.1.0rc1.tar.gz#md5=c6e44c9e70e53b1519a4d107701b4aaa (from https://pypi.python.org/simple/resampy/), version: 0.1.0rc1
  Using version 0.1.3 (newest of versions: 0.1.0, 0.1.2, 0.1.3)
  Looking up "https://pypi.python.org/packages/2b/5e/3a85b22a52f44709d228aabe0985d674124c23ce9589bd8c27a609c8ad1b/resampy-0.1.3.tar.gz" in the cache
  No cache entry available
  "GET /packages/2b/5e/3a85b22a52f44709d228aabe0985d674124c23ce9589bd8c27a609c8ad1b/resampy-0.1.3.tar.gz HTTP/1.1" 200 442689
  Downloading resampy-0.1.3.tar.gz (442kB)
  Downloading from URL https://pypi.python.org/packages/2b/5e/3a85b22a52f44709d228aabe0985d674124c23ce9589bd8c27a609c8ad1b/resampy-0.1.3.tar.gz#md5=cafebf87cd908d2a35f2f4ac1e95ddb6 (from https://pypi.python.org/simple/resampy/)
    99% |███████████████████████████████▉| 440kB 18.1MB/s eta 0:00:01  Updating cache with response from "https://pypi.python.org/packages/2b/5e/3a85b22a52f44709d228aabe0985d674124c23ce9589bd8c27a609c8ad1b/resampy-0.1.3.tar.gz"
  Caching due to etag
    100% |████████████████████████████████| 450kB 1.4MB/s 
  Running setup.py (path:/tmp/pip-build-PN8FTG/resampy/setup.py) egg_info for package resampy
    Running command python setup.py egg_info
    running egg_info
    creating pip-egg-info/resampy.egg-info
    writing requirements to pip-egg-info/resampy.egg-info/requires.txt
    writing pip-egg-info/resampy.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/resampy.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/resampy.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/resampy.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'pip-egg-info/resampy.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.pxd' under directory 'resampy'
    writing manifest file 'pip-egg-info/resampy.egg-info/SOURCES.txt'
  Source in /tmp/pip-build-PN8FTG/resampy has version 0.1.3, which satisfies requirement resampy from https://pypi.python.org/packages/2b/5e/3a85b22a52f44709d228aabe0985d674124c23ce9589bd8c27a609c8ad1b/resampy-0.1.3.tar.gz#md5=cafebf87cd908d2a35f2f4ac1e95ddb6
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.10 in /usr/local/lib/python2.7/dist-packages (from resampy)
Requirement already satisfied (use --upgrade to upgrade): scipy>=0.13 in /usr/local/lib/python2.7/dist-packages (from resampy)
Requirement already satisfied (use --upgrade to upgrade): six>=1.3 in /usr/lib/python2.7/dist-packages (from resampy)
Requirement already satisfied (use --upgrade to upgrade): Cython>=0.23 in /usr/local/lib/python2.7/dist-packages (from resampy)
Installing collected packages: resampy
  Running setup.py install for resampy ...     Running command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-PN8FTG/resampy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-jWa0nu-record/install-record.txt --single-version-externally-managed --compile
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/resampy
    copying resampy/__init__.py -> build/lib.linux-x86_64-2.7/resampy
    copying resampy/core.py -> build/lib.linux-x86_64-2.7/resampy
    copying resampy/version.py -> build/lib.linux-x86_64-2.7/resampy
    copying resampy/filters.py -> build/lib.linux-x86_64-2.7/resampy
    creating build/lib.linux-x86_64-2.7/resampy/data
    copying resampy/data/kaiser_best.npz -> build/lib.linux-x86_64-2.7/resampy/data
    copying resampy/data/kaiser_fast.npz -> build/lib.linux-x86_64-2.7/resampy/data
    running build_ext
    skipping 'resampy/interp.c' Cython extension (up-to-date)
    building 'resampy.interp' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/resampy
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c resampy/interp.c -o build/temp.linux-x86_64-2.7/resampy/interp.o
    resampy/interp.c:4:20: fatal error: Python.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
error
Cleaning up...
  Removing source in /tmp/pip-build-PN8FTG/resampy
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-PN8FTG/resampy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-jWa0nu-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-PN8FTG/resampy/
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip-8.1.2-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip-8.1.2-py2.7.egg/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/dist-packages/pip-8.1.2-py2.7.egg/pip/req/req_set.py", line 742, in install
    **kwargs
  File "/usr/local/lib/python2.7/dist-packages/pip-8.1.2-py2.7.egg/pip/req/req_install.py", line 880, in install
    spinner=spinner,
  File "/usr/local/lib/python2.7/dist-packages/pip-8.1.2-py2.7.egg/pip/utils/__init__.py", line 718, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-PN8FTG/resampy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-jWa0nu-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-PN8FTG/resampy/
```

**Comment by bmcfee** [comment]
@DomagojHack Can you try a `pip install --pre resampy` now?  0.1.4rc0 is up, and (I hope) should fix your install issue.

**Comment by DomagojHack** [comment]
I tried and it passed successfully with no problems.

Cheers.

**Comment by bmcfee** [comment]
Great, thanks!
