### ISSUE TITLE
undefined symbol: PyFPE_jbuf

### ISSUE THREAD

**Issue by arpitbaheti** [bmcfee/resampy#49]
```
$ python --version
Python 2.7.13 :: Continuum Analytics, Inc.

$python -c "import librosa; print(librosa.__version__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/arpitb/anaconda3/envs/speaker-id/lib/python2.7/site-packages/librosa/__init__.py", line 11, in <module>
    from . import core
  File "/home/arpitb/anaconda3/envs/speaker-id/lib/python2.7/site-packages/librosa/core/__init__.py", line 109, in <module>
    from .audio import *  # pylint: disable=wildcard-import
  File "/home/arpitb/anaconda3/envs/speaker-id/lib/python2.7/site-packages/librosa/core/audio.py", line 12, in <module>
    import resampy
  File "/home/arpitb/anaconda3/envs/speaker-id/lib/python2.7/site-packages/resampy/__init__.py", line 7, in <module>
    from .core import *
  File "/home/arpitb/anaconda3/envs/speaker-id/lib/python2.7/site-packages/resampy/core.py", line 8, in <module>
    from .interp import resample_f
ImportError: /home/arpitb/anaconda3/envs/speaker-id/lib/python2.7/site-packages/resampy/interp.so: undefined symbol: PyFPE_jbuf
```

**Comment by bmcfee** [comment]
Wow, that is not one that I've seen before.  This [thread](https://stackoverflow.com/questions/36190757/numpy-undefined-symbol-pyfpe-jbuf) might be relevant for you though; it looks like it might be a conflict between conda and pip packages.  Did you happen to install one of the core dependencies (numpy, cython, etc) through pip instead of conda?

**Comment by bmcfee** [comment]
I'm closing this one out, since the 0.2.0 release is now up and should fix this problem.  Please re-open if the problem persists.
